pod 'AFNetworking'
pod 'GCDObjC'
pod 'BlocksKit'
pod 'ReactiveCocoa'
pod 'SDWebImage'
pod 'UIColor-Utilities', '~> 1.0.1'
pod 'MBProgressHUD'
pod 'Mantle'
pod 'CocoaHTTPServer', '~> 2.3'
pod 'MagicalRecord', '~> 2.2'
pod 'FMDB', '~> 2.4'
pod 'UzysAnimatedGifPullToRefresh'
pod 'pop', '~> 1.0.7'
